[Python_General]
IS_LOGGING_ENABLED = 1
IS_DEBUG_ENABLED = 1
MAX_ACTIVE_PLAYERS_FOR_LOW_ONLINE = 10
SCHEDULER_IS_ENABLED = 0
GAME_PRIVILEGES_ARE_ENABLED = 0
SERVER_URL = https://savagedrx.com
DISCORD_URL = https://tinyurl.com/drx-discord

[Python_Discord]
DISCORD_IS_ENABLED = 0
DISCORD_CHANNEL = 552093259443470338
DISCORD_GUILD_ID = 552093259443470336

[Python_Afk]
AFK_IS_ENABLED = 0
AFK_INITIAL_PRE_CHECK_SECONDS = 10
AFK_SINGLE_CHECKOUT_SECONDS = 30
AFK_INTERVAL_CHECKOUT_MINUTES = 2

[Python_Stats]
STATS_ENDGAME_PUBLISHER_ENABLED = 0
STATS_UPDATER_PLAYER_STATE_INTERVAL_MINUTES = 1

[Python_Maps]
IS_WORLD_LIST_ENABLED = 0
WORLD_LIST_FILE_NAME = ./config/world_list.cfg
SKIP_MAP_CHECK = 1

[Python_Bans]
IS_BAN_ENABLED = 0
BANNED_IPS_FILE_NAME = banned_ips.cfg
IS_CHAT_BAN_ENABLED = 0
BANNED_WORDS_FILE_NAME = banned_words.cfg

[Python_Warmup]
IS_WARMUP_ENABLED = 0
ON_FRAME_EVENT_INTERVAL_SECONDS = 20
GIVE_STATE_DURATION_SECONDS = 10

[Credentials]
;; only svr_password can have an empty value
svr_password =
svr_PasswordVIP = vip123
sv_refereePassword = ref456
sv_refGodPassword = godref789
DISCORD_TOKEN = 12345

[Silverback_General]
svr_name = ^gUnnamed ^gServer        ^y(DEV)
default_world = izi
svr_broadcast = 0
svr_port = 11235
sv_authserver = https://api.savagedrx.com/metaserver/v1/
sv_joinTeamAuth = 1

host_maxfps = 200
svr_gamefps = 40
svr_realfps = 40

;; ___ MESSAGE OF THE DAY ______________________________________________________________________________________________
sv_motd1 = ^gWelcome ^gto ^yUnnamed ^yServer ^y(DEV)
sv_motd2 =
sv_motd3 =
sv_motd4 =
sv_motd5 =
sv_motd6 =

sv_refereePassword = 111
sv_refGodPassword = 222
g_allUnitsAvailable = 1
g_allWeaponsAvailable = 1
sv_allowEnemySameIP = 1
sv_infiniteGold = 1
sv_infiniteResources = 1
sv_balancedTeams = 0
sv_fastTech = 1
sv_commSpawnSiege = 1
sv_voteduration = 20000
sv_voteConnectInterval = 0
; sv_xp_mult = 1000.0
; sv_xp_kill_npc = 1000.0
; sv_xp_build = 1000.0
host_fpsinterval = 0

[Silverback_Referees]
;; JSON of the {"player_id": "player_name"}
god_refs = {"2": "drk", "9": "Noxx"}
normal_refs = {}

[Python_Referees]
PYTHON_ADMIN_IDS = [1, 2]
PYTHON_REF_IDS = [1, 2]

[Silverback_Server_Registration]
sv_authid = 99999
sv_authtoken = 12345
svr_hostname = 192.168.0.1